package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPLICANT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "APPLICANT_ID_SEQ", name = "APPLICANT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Applicant Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "Social Security Number")
   private java.lang.Integer ssn;

   @org.kie.api.definition.type.Label(value = "Annual Income")
   private java.lang.Integer income;

   @org.kie.api.definition.type.Label(value = "Credit Score")
   private java.lang.Integer creditScore;

   public Applicant()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.Integer ssn)
   {
      this.ssn = ssn;
   }

   public java.lang.Integer getIncome()
   {
      return this.income;
   }

   public void setIncome(java.lang.Integer income)
   {
      this.income = income;
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public Applicant(java.lang.Long id, java.lang.String name,
         java.lang.Integer ssn, java.lang.Integer income,
         java.lang.Integer creditScore)
   {
      this.id = id;
      this.name = name;
      this.ssn = ssn;
      this.income = income;
      this.creditScore = creditScore;
   }

}