package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Property implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROPERTY_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROPERTY_ID_SEQ", name = "PROPERTY_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Property Address")
   private java.lang.String address;

   @org.kie.api.definition.type.Label(value = "Sale Price")
   private java.lang.Integer price;

   public Property()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Integer getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Integer price)
   {
      this.price = price;
   }

   public Property(java.lang.Long id, java.lang.String address,
         java.lang.Integer price)
   {
      this.id = id;
      this.address = address;
      this.price = price;
   }

}